[tool.poetry]
name = "model"
version = "0.1.0"
description = ""
authors = ["shmbrg <sebastian.humberg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mlflow = "^1.24.0"
sklearn = "^0.0"
lightgbm = "^3.3.2"
pandas = "^1.4.1"
matplotlib = "^3.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
